import type { Metadata } from "next";
import { Mail, MapPin, MessageCircle, Phone } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { Button } from "@/components/shared/Button";
import { PageHero } from "@/components/shared/PageHero";
import { ResponsiveImage } from "@/components/shared/ResponsiveImage";
import { SectionHeading } from "@/components/shared/SectionHeading";
import { getSiteSettings } from "@/lib/content";
import { SectionOrnament } from "@/components/shared/SectionOrnament";

export const metadata: Metadata = { title: "Visit Us", description: "Plan a visit to OSHO Mystery School Nepal near Kathmandu." };

export default function VisitPage() {
  const settings = getSiteSettings();
  const contacts: Array<[LucideIcon, string, string | undefined, string]> = [
    [MessageCircle,"WhatsApp",settings.whatsapp,"Fastest response for retreat inquiries"],
    [Mail,"Email",settings.email,"Write to us with your questions"],
    [Phone,"Phone",settings.phone,"Call when you need to speak with us"],
    [MapPin,"Address",settings.address,"Kathmandu, Nepal"],
  ];
  return (
    <>
      <PageHero title="Come as You Are" copy="Whether you are planning a retreat or simply curious about a day visit, we would be happy to help you find your way here." label="Visit Hero Image" light={false} accent="sage"/>
      <section className="section container relative overflow-hidden"><SectionOrnament motif="bloom" position="top-right" tone="terracotta" opacity={0.3}/><div className="relative z-10 grid gap-16 lg:grid-cols-12"><div className="lg:col-span-5"><SectionHeading eyebrow="Contact" title="Let’s Begin a Conversation" /><div className="space-y-8">{contacts.map(([Icon,title,value,note])=>{const ContactIcon=Icon as typeof Mail; return <div key={String(title)} className="flex gap-5"><ContactIcon className="mt-1 shrink-0 text-[var(--terracotta-bright)]"/><div><h3 className="label text-[var(--forest)]">{String(title)}</h3><p className="mt-1 text-[var(--muted)]">{value || "To be confirmed"}</p><p className="mt-1 text-xs text-[var(--muted)]/70">{String(note)}</p></div></div>})}</div></div><div className="rounded-[8px] bg-[var(--surface-low)] p-8 sm:p-12 lg:col-span-7"><h2 className="text-3xl text-[var(--forest)]">Send a Message</h2><form name="contact" method="POST" data-netlify="true" className="mt-10 grid gap-8 md:grid-cols-2"><input type="hidden" name="form-name" value="contact"/><label className="label text-[var(--forest)]">Your name<input required name="name" autoComplete="name" className="mt-3 w-full border-0 border-b border-[var(--forest)]/30 bg-transparent px-0 py-3 normal-case tracking-normal outline-none focus:border-[var(--forest)]"/></label><label className="label text-[var(--forest)]">Email<input required type="email" name="email" autoComplete="email" className="mt-3 w-full border-0 border-b border-[var(--forest)]/30 bg-transparent px-0 py-3 normal-case tracking-normal outline-none focus:border-[var(--forest)]"/></label><label className="label text-[var(--forest)] md:col-span-2">What brings you here?<select name="interest" className="mt-3 w-full border-0 border-b border-[var(--forest)]/30 bg-transparent px-0 py-3 normal-case tracking-normal outline-none"><option>General question</option><option>Meditation</option><option>Retreat</option><option>Stay</option><option>Event</option></select></label><label className="label text-[var(--forest)] md:col-span-2">Message<textarea required name="message" rows={5} className="mt-3 w-full resize-y border-0 border-b border-[var(--forest)]/30 bg-transparent px-0 py-3 normal-case tracking-normal outline-none focus:border-[var(--forest)]"/></label><button type="submit" className="label min-h-12 rounded-[4px] bg-[var(--terracotta-bright)] px-8 py-4 text-white hover:bg-[var(--terracotta)] md:w-fit">Send Message</button></form></div></div></section>
      <section className="section relative overflow-hidden bg-[linear-gradient(145deg,#eef2eb,#f7efe7)]"><SectionOrnament motif="himalaya" position="bottom-left" tone="sage" opacity={0.3}/><div className="container relative z-10 grid items-center gap-16 lg:grid-cols-2"><div><SectionHeading eyebrow="Getting here" title="In the Foothills Near Kathmandu" /><p className="lede">Contact the school before travelling so we can share the current directions and help coordinate your arrival.</p><p className="mt-5 text-[var(--muted)]">Travel times vary with Kathmandu traffic and your point of departure. We will provide practical, up-to-date guidance when your visit is confirmed.</p>{settings.mapsLink && <Button href={settings.mapsLink} variant="secondary" className="mt-9">Open Map</Button>}</div><ResponsiveImage label="Map / Location Image" aspect="4 / 3" placeholderTone="sage" className="rounded-[12px] border border-[var(--forest)]/10"/></div></section>
      <section className="section container relative overflow-hidden"><SectionOrnament motif="lotus" position="bottom-right" tone="terracotta" opacity={0.3}/><div className="relative z-10"><SectionHeading eyebrow="Before you come" title="A Few Useful Answers" center/><div className="grid gap-8 md:grid-cols-3">{[["Prior Experience?","No previous meditation experience is necessary. Come with curiosity and comfortable clothes."],["What to Bring?","We will share a simple packing list once your visit or stay is confirmed."],["Day Visits?","Please contact us first so we can tell you which meditations and visiting times are available."]].map(([title,copy])=><article key={title} className="rounded-[8px] bg-[var(--surface-high)] p-8"><h3 className="text-2xl text-[var(--forest)]">{title}</h3><p className="mt-4 text-[var(--muted)]">{copy}</p></article>)}</div></div></section>
      <section className="section section-low text-center"><div className="container"><h2 className="display text-[var(--forest)]">Your Journey Can Begin Here</h2><p className="lede mx-auto mt-6 max-w-xl">Send us a message and we will help you understand the simplest next step.</p><Button href={settings.bookingLink ?? "/retreats"} className="mt-9">Book a Retreat</Button></div></section>
    </>
  );
}
