import type { Metadata } from "next";
import { Button } from "@/components/shared/Button";
import { ContentCard } from "@/components/shared/ContentCard";
import { EmptyState } from "@/components/shared/EmptyState";
import { PageHero } from "@/components/shared/PageHero";
import { ResponsiveImage } from "@/components/shared/ResponsiveImage";
import { SectionHeading } from "@/components/shared/SectionHeading";
import { SectionOrnament } from "@/components/shared/SectionOrnament";
import { getCollection, getPage } from "@/lib/content";

export const metadata: Metadata = { title: "Retreats & Programs", description: "Residential meditation retreats and programs near Kathmandu, Nepal." };

export default function RetreatsPage() {
  const retreats = getCollection("retreats");
  const page = getPage("retreats");
  return (
    <>
      <PageHero title="Time to Go Deeper" copy="Step out of the familiar and enter a rhythm of meditation, nature, nourishing food, silence, and celebration." label="Retreat Hero Image" image={page.heroImage} imageAlt={page.heroAlt ?? "A retreat at OSHO Mystery School Nepal"} light={false} accent="gold" />
      <section className="section container relative overflow-hidden text-center"><SectionOrnament motif="lotus" position="bottom-left" tone="terracotta" opacity={0.3}/><div className="relative z-10"><p className="mx-auto max-w-4xl text-3xl leading-relaxed text-[var(--forest)] md:text-4xl">A retreat is not an escape from life. It is a chance to meet life with fewer distractions and a little more honesty.</p><p className="lede mx-auto mt-8 max-w-2xl">Programs range from short weekend immersions to longer residential journeys.</p></div></section>
      <section className="section section-low relative overflow-hidden"><SectionOrnament motif="angles" position="top-right" tone="sage" opacity={0.3}/><div className="container relative z-10"><SectionHeading eyebrow="Coming up" title="Retreats & Camps" copy="Schedules and availability are published here as soon as they are confirmed." />{retreats.length ? <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">{retreats.map(item=><ContentCard key={item.slug} item={item} label="Retreat Image" href={`/retreats/${item.slug}`} />)}</div> : <EmptyState message="There are no published retreats right now. Please contact us for the latest schedule." />}</div></section>
      <section className="section container relative grid items-center gap-16 overflow-hidden lg:grid-cols-2"><SectionOrnament motif="himalaya" position="bottom-right" tone="sage" opacity={0.3}/><ResponsiveImage src={page.residentialImage} alt={page.residentialImageAlt ?? "Residential life at the Mystery School"} label="Residential Program Image" aspect="4 / 5" className="relative z-10 rounded-[8px]" /><div className="relative z-10"><SectionHeading eyebrow="Residential programs" title="Live the Rhythm of the School" /><p className="lede">A longer stay gives the practices time to settle. Mornings begin with active meditation; the day unfolds through work, rest, shared meals, nature, and evening silence.</p><p className="mt-5 text-[var(--muted)]">Programs are held in a simple, supportive environment. No belief or previous experience is required.</p><Button href="/stay" variant="secondary" className="mt-9">Explore the Stay</Button></div></section>
      <section className="section section-low relative overflow-hidden"><SectionOrnament motif="bloom" position="top-left" tone="terracotta" opacity={0.3}/><div className="container relative z-10"><SectionHeading eyebrow="Gatherings" title="Special Events" copy="Seasonal celebrations, meditation days, music, and moments of shared silence." /><div className="grid min-h-[580px] gap-6 md:grid-cols-3"><article className="group relative overflow-hidden rounded-[8px] md:col-span-2"><ResponsiveImage src={page.fullMoonImage} alt={page.fullMoonImageAlt ?? "Full moon meditation gathering"} label="Full Moon Meditation Image" aspect="16 / 9" className="absolute inset-0 h-full w-full"/><div className="absolute inset-0 bg-gradient-to-t from-[var(--forest)]/90 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-8 text-white"><h3 className="text-3xl">Full Moon Meditations</h3><p className="mt-3 max-w-xl text-white/70">Guided practice and silent sitting beneath the open sky.</p></div></article><div className="grid gap-6"><article className="group relative min-h-64 overflow-hidden rounded-[8px]"><ResponsiveImage src={page.musicImage} alt={page.musicImageAlt ?? "Music and celebration gathering"} label="Music Gathering Image" aspect="4 / 3" className="absolute inset-0 h-full w-full"/><div className="absolute inset-0 bg-[var(--forest)]/50"/><h3 className="absolute bottom-6 left-6 text-2xl text-white">Music & Celebration</h3></article><article className="flex min-h-64 flex-col justify-end rounded-[8px] bg-[#fd9171] p-7 text-[var(--forest)]"><h3 className="text-2xl">OSHO Celebration Days</h3><p className="mt-3 text-sm opacity-70">Meditation, creativity, friendship, and joy.</p></article></div></div></div></section>
    </>
  );
}
